name: rice_cooker
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^2.15.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  test: any
