version: 2.1

jobs:
  test:
    docker:
      - image: google/dart:latest
    steps:
      - checkout
      - run: dart test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              only: feature/dart
