version: 2.1

jobs:
  build:
    docker:
      - image: google/dart:latest

    steps:
      - checkout

      - run:
          name: Run tests
          command: dart test

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - feature/dart